# Generated by Django 5.2.8 on 2025-11-29 02:48

from django.db import migrations, models


def set_share_limit_for_existing_users(apps, schema_editor):
    """既存ユーザーのshare_limitを設定"""
    User = apps.get_model('users', 'User')
    # 無料ユーザー: 1, プレミアムユーザー: 5
    User.objects.filter(is_subscribed=False).update(share_limit=1)
    User.objects.filter(is_subscribed=True).update(share_limit=5)


def reverse_set_share_limit(apps, schema_editor):
    """ロールバック時の処理（特に必要な処理はなし）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='share_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(set_share_limit_for_existing_users, reverse_set_share_limit),
    ]
