# Generated by Django 6.0 on 2026-01-02 08:14

from django.db import migrations, models


def migrate_plan_type(apps, schema_editor):
    """既存のis_subscribedフィールドからplan_typeへデータを移行"""
    User = apps.get_model('users', 'User')

    # is_subscribed=True → BASIC (既存の有料プラン相当)
    User.objects.filter(is_subscribed=True).update(plan_type='BASIC')

    # is_subscribed=False → FREE (無料プラン)
    User.objects.filter(is_subscribed=False).update(plan_type='FREE')


def reverse_migrate_plan_type(apps, schema_editor):
    """ロールバック時の処理"""
    User = apps.get_model('users', 'User')

    # BASIC, PREMIUM, UNLIMITED → is_subscribed=True
    User.objects.filter(plan_type__in=['BASIC', 'PREMIUM', 'UNLIMITED']).update(is_subscribed=True)

    # FREE → is_subscribed=False
    User.objects.filter(plan_type='FREE').update(is_subscribed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_share_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('UNLIMITED', 'Unlimited')], default='FREE', max_length=20),
        ),
        migrations.RunPython(migrate_plan_type, reverse_migrate_plan_type),
    ]
