# Generated by Django 6.0 on 2026-01-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preset_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='share_limit',
        ),
    ]
