# Generated by Django 6.0.5 on 2026-05-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_plan_type_and_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deactivated_at',
        ),
    ]
