steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - asia-northeast1-docker.pkg.dev/roamble/roamble/backend:latest
      - -f
      - backend/Dockerfile.prod
      - backend

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - asia-northeast1-docker.pkg.dev/roamble/roamble/backend:latest

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - roamble-backend
      - --image=asia-northeast1-docker.pkg.dev/roamble/roamble/backend:latest
      - --region=asia-northeast1
      - --min-instances=0

images:
  - asia-northeast1-docker.pkg.dev/roamble/roamble/backend:latest

options:
  logging: CLOUD_LOGGING_ONLY
