# Generated by Django 5.1.6 on 2025-02-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ice_g'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipestep',
            old_name='water_ml_this_step',
            new_name='total_water_ml_this_step',
        ),
    ]
