# Generated by Django 5.1.6 on 2025-05-30 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_water_ml_this_step_recipestep_total_water_ml_this_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_ice', models.BooleanField(default=False)),
                ('ice_g', models.FloatField(blank=True, null=True)),
                ('len_steps', models.IntegerField()),
                ('bean_g', models.FloatField()),
                ('water_ml', models.FloatField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('shared_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedRecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('total_water_ml_this_step', models.FloatField()),
                ('shared_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.sharedrecipe')),
            ],
        ),
    ]
