# Generated by Django 5.2.6 on 2025-09-26 01:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_sharedrecipe_sharedrecipestep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='PresetRecipe',
        ),
        migrations.RenameModel(
            old_name='RecipeStep',
            new_name='PresetRecipeStep',
        ),
    ]
