# Generated by Django 5.2.6 on 2025-09-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_recipe_presetrecipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedrecipe',
            name='expires_at',
        ),
    ]
