# Generated by Django 5.2.6 on 2025-09-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_expires_at_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedrecipestep',
            old_name='shared_recipe',
            new_name='recipe_id',
        ),
    ]
