# Generated by Django 5.2.6 on 2025-09-26 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_shared_recipe_to_recipe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presetrecipestep',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='sharedrecipestep',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
