# Generated by Django 5.2.6 on 2025-09-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_recipe_id_to_recipe'),
        ('users', '0006_alter_user_is_subscribed'),
    ]

    operations = [
        # PresetRecipeのcreate_userをcreated_byにリネーム
        migrations.RenameField(
            model_name='presetrecipe',
            old_name='create_user',
            new_name='created_by',
        ),
        # SharedRecipeのshared_by_userをcreated_byにリネーム
        migrations.RenameField(
            model_name='sharedrecipe',
            old_name='shared_by_user',
            new_name='created_by',
        ),
    ]
